### ISSUE TITLE
About the difference between edge_index(edge_type) with edge_index_ori(edge_type_ori)

### ISSUE THREAD

**Issue by orion-orion** [zjukg/FedE#2]
Hello, I want to know about the difference between edge_index(edge_type) with edge_index_ori(edge_type_ori). I think each index of entity/relation on a client should be also the global index in the entire knowledge graph, so I don't understand why there exist local indices here. I'm sincerely looking forward to your reply, thank you.😊

**Comment by AnselCmy** [comment]
Thanks for your interest. edge_index and edge_type are new indexes in some specific clients and edge_index_ori and edge_type_ori use original indexed in original KGs. In our implementation, we use the original entity index (edge_index_ori) and local relation index (edge_type) during training FedE, and we use edge_index_ori and edge_type_ori during training Collection. The details can be found in dataloader.py.

**Comment by orion-orion** [comment]
Thanks for your reply, but I still have a question about how to map original entity(relation) indices into local entity(relation) indices. For example, we consider dividing the entity into two clients, if global endity indices are [0, 1, 2, 3], are local indices in two clients [0, 1], [0, 1](with renumbering)?

**Comment by AnselCmy** [comment]
During model training, you don't need to map local indices into global indices. For example, when training FedE, we use original indices for entities and there is no need to map indices.

**Comment by orion-orion** [comment]
Yes, but in "Single setting"(only using the local knowledge graph) , the code also map global entity indices into local entity indices as follows:
```python
In [39]: print(sorted(all_data[1]['train']['edge_index'].flatten())[:50])
[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [40]: print(sorted(all_data[1]['train']['edge_index_ori'].flatten())[:50])
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
```
This seems to be irregular, how does the mapping work here?

**Comment by AnselCmy** [comment]
We maintain edge_index, edge_index_ori, edge_type and edge_type_ori in all settings, and this is predefined before training. However, during "Single setting", we only use local renumbered indices (from line 143 in dataloader.py), i.e., edge_index and edge_type.

**Comment by orion-orion** [comment]
Thanks for your patience，but I still have a problem.  According to the code above, there are ten 0 in edge_index_ori, whereas six 0 in edge_index, why is the number of 0 not the same?(I think the number of 0 should be the same after renumbering).

**Comment by AnselCmy** [comment]
According to our dataset split method, we split the relation set into c clients, and different clients have different relations. Thus, the relation of index 0 in edge_index_ori and the relation of index 0 in edge_index may not be the same relation.

**Comment by orion-orion** [comment]
Consider the following code:
```python
In [19]: collections.Counter(all_data[1]['train']['edge_index_ori'].flatten())
    ...: .most_common(5)
Out[19]: [(32, 2199), (90, 2106), (160, 1555), (23, 1353), (9, 952)]

In [20]: collections.Counter(all_data[1]['train']['edge_index'].flatten()).mos
    ...: t_common(5)
Out[20]: [(10, 2199), (36, 2106), (68, 1555), (5, 1353), (319, 952)]
```
I don't know if my understanding below is correct: 32 maps to 10，90 maps to 36, 160 maps to 68, etc. Is the mapping here random?

**Comment by AnselCmy** [comment]
Yes, your understanding is correct and it's random.

**Comment by orion-orion** [comment]
OK, thanks a lot for your reply❤️
